// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heklatbqyruofngbxpkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhla2xhdGJxeXJ1b2ZuZ2J4cGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTI3NjAsImV4cCI6MjA2OTM4ODc2MH0.flKjLDY3IGcMMvmYKIWqfGoXeYSCtqfq1LIIYOrHcVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});